"""
Training Script for Cart Add-to-Cart Prediction Model

Trains the CartAddToCartModel on cart event data with:
- Dynamic padding for variable-length cart sequences
- BCEWithLogitsLoss with class weighting for imbalance
- AdamW optimizer with learning rate scheduling
- Time-based train/validation split
- Comprehensive logging (loss, AUC, PR-AUC)

Memory Requirements:
- Designed to run on CPU with < 8GB RAM
- Uses chunked data loading and gradient checkpointing

Usage:
    python -m src.model.train_model
    python -m src.model.train_model --batch-size 2048 --epochs 10
    python -m src.model.train_model --sample-size 5000000  # Train on subset

Author: ZOMATHON Team
Date: February 2026
"""

import argparse
import gc
import logging
import pickle
import sys
import time
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR, ReduceLROnPlateau
from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler
from sklearn.metrics import roc_auc_score, average_precision_score

from src.model.cart_transformer import CartAddToCartModel, create_cart_mask


# -----------------------------------------------------------------------------
# Logging Configuration
# -----------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("logs/training.log", mode="a")
    ]
)
logger = logging.getLogger(__name__)


# -----------------------------------------------------------------------------
# Constants & Paths
# -----------------------------------------------------------------------------

# Data paths
CART_EVENTS_PATH = Path("data/synthetic/cart_events.csv")
EMBEDDINGS_PATH = Path("data/processed/item_embeddings_fixed.npy")
ITEM_MAPPING_PATH = Path("data/processed/item_id_mapping.pkl")
USERS_PATH = Path("data/synthetic/users.csv")
RESTAURANTS_PATH = Path("data/processed/restaurants_cleaned.csv")
MENU_ITEMS_PATH = Path("data/processed/menu_items_simulation.csv")

# Normalized feature paths (generated by feature_builder.py)
USER_FEATURES_PATH = Path("data/processed/user_features.parquet")
RESTAURANT_FEATURES_PATH = Path("data/processed/restaurant_features.parquet")
FEATURE_SCALERS_PATH = Path("data/processed/feature_scalers.pkl")

# Output paths
CHECKPOINTS_DIR = Path("checkpoints")
LOGS_DIR = Path("logs")

# Training defaults
DEFAULT_BATCH_SIZE = 2048
DEFAULT_EPOCHS = 10
DEFAULT_LR = 1e-3
DEFAULT_SAMPLE_SIZE = 5_000_000  # Train on 5M rows initially
DEFAULT_VAL_RATIO = 0.1  # Last 10% for validation (time-based)
MAX_CART_SIZE = 10

# Category mappings
MEAL_TYPE_MAP = {
    "breakfast": 0, "lunch": 1, "snack": 2, 
    "dinner": 3, "late_night": 4
}
USER_TYPE_MAP = {
    "budget": 0, "moderate": 1, "premium": 2, "luxury": 3
}


# -----------------------------------------------------------------------------
# Data Structures
# -----------------------------------------------------------------------------

@dataclass
class TrainingSample:
    """Single training sample with all required features."""
    cart_indices: List[int]      # Item embedding indices in cart
    candidate_index: int         # Candidate item embedding index
    label: int                   # 1 = added, 0 = not added
    user_features: List[float]   # User feature vector
    restaurant_features: List[float]  # Restaurant feature vector
    cart_dynamic_features: List[float]  # Cart total, size, avg price, missing_beverage, missing_dessert, heavy_meal
    context_features: List[float]  # Hour, meal_type, user_type
    timestamp: str               # For time-based splitting


# -----------------------------------------------------------------------------
# Dataset Class
# -----------------------------------------------------------------------------

class CartDataset(Dataset):
    """
    PyTorch Dataset for cart add-to-cart prediction.
    
    Handles:
    - Loading and preprocessing cart event data
    - Feature extraction from multiple sources
    - Index mapping for item embeddings
    
    Memory-efficient: stores only essential data, computes features on-the-fly.
    """
    
    def __init__(
        self,
        cart_events_df: pd.DataFrame,
        item_id_to_idx: Dict[str, int],
        user_features_df: Optional[pd.DataFrame] = None,
        restaurant_features_df: Optional[pd.DataFrame] = None,
        menu_items_df: Optional[pd.DataFrame] = None
    ):
        """
        Initialize dataset from preprocessed DataFrames.
        
        Args:
            cart_events_df: DataFrame with cart event columns
            item_id_to_idx: Mapping from item_id to embedding index
            user_features_df: Pre-computed user features (optional)
            restaurant_features_df: Pre-computed restaurant features (optional)
            menu_items_df: Menu items for price lookup (optional)
        """
        self.item_id_to_idx = item_id_to_idx
        self.data = []
        
        # Default user features (normalized values, should be ~0 mean, ~1 std)
        self.default_user_features = [0.0, 0.0, 0.0, 0.5, 0.0, 0.1, 0.15]
        
        # Default restaurant features (normalized values)
        self.default_restaurant_features = [0.25, 0.0, 0.0, 0.5, 0.0]
        
        # Build user feature lookup using normalized columns
        self.user_features_lookup: Dict[str, List[float]] = {}
        if user_features_df is not None:
            # Require normalized columns (no fallback)
            if "recency_days_norm" not in user_features_df.columns:
                raise ValueError("User features must have _norm columns. Run feature_builder.py first.")
            
            for _, row in user_features_df.iterrows():
                self.user_features_lookup[row["user_id"]] = [
                    float(row.get("recency_days_norm", 0.0)),
                    float(row.get("frequency_norm", 0.0)),
                    float(row.get("monetary_avg_norm", 0.0)),
                    float(row.get("cuisine_entropy_norm", 0.5)),
                    float(row.get("avg_cart_size_norm", 0.0)),
                    float(row.get("dessert_ratio_norm", 0.1)),
                    float(row.get("beverage_ratio_norm", 0.15)),
                ]
        
        # Build restaurant feature lookup using normalized columns
        self.restaurant_features_lookup: Dict[str, List[float]] = {}
        if restaurant_features_df is not None:
            # Require normalized columns (no fallback)
            if "smoothed_rating_norm" not in restaurant_features_df.columns:
                raise ValueError("Restaurant features must have _norm columns. Run feature_builder.py first.")
            
            for _, row in restaurant_features_df.iterrows():
                self.restaurant_features_lookup[row["restaurant_id"]] = [
                    float(row.get("smoothed_rating_norm", 0.25)),
                    float(row.get("delivery_votes_norm", 0.0)),
                    float(row.get("avg_item_price_norm", 0.0)),
                    float(row.get("price_band_index_norm", 0.5)),
                    float(row.get("menu_size_norm", 0.0)),
                ]
        
        # Build item price lookup and category lookup
        self.item_prices: Dict[str, float] = {}
        self.item_categories: Dict[str, int] = {}  # item_id -> category_index (0=main, 1=starter, 2=dessert, 3=beverage, 4=side)
        if menu_items_df is not None:
            for _, row in menu_items_df.iterrows():
                self.item_prices[row["item_id"]] = float(row.get("price", 100))
                # Map category string to index
                cat = str(row.get("item_category", "other")).lower()
                cat_map = {"main": 0, "starter": 1, "dessert": 2, "beverage": 3, "side": 4, "snack": 5, "combo": 6, "other": 7}
                self.item_categories[row["item_id"]] = cat_map.get(cat, 7)
        
        # Process cart events
        self._process_events(cart_events_df)
        
        logger.info(f"CartDataset initialized with {len(self.data):,} samples")
    
    def _process_events(self, df: pd.DataFrame):
        """Process cart events into training samples."""
        for _, row in df.iterrows():
            # Parse cart items
            cart_items_str = str(row.get("cart_items", ""))
            if cart_items_str and cart_items_str != "nan":
                cart_item_ids = [x.strip() for x in cart_items_str.split("|") if x.strip()]
            else:
                cart_item_ids = []
            
            # Convert to embedding indices (shift by +1, 0 is padding)
            cart_indices = []
            for item_id in cart_item_ids[:MAX_CART_SIZE]:  # Truncate to max size
                idx = self.item_id_to_idx.get(item_id, -1)
                if idx >= 0:
                    cart_indices.append(idx + 1)  # +1 for padding index
            
            # Get candidate item index
            candidate_id = row.get("candidate_item", "")
            candidate_idx = self.item_id_to_idx.get(candidate_id, -1)
            if candidate_idx < 0:
                continue  # Skip if candidate not in embeddings
            candidate_idx += 1  # +1 for padding
            
            # Get label
            label = int(row.get("label", 0))
            
            # User features
            user_id = row.get("user_id", "")
            user_features = self.user_features_lookup.get(
                user_id, self.default_user_features.copy()
            )
            
            # Restaurant features
            restaurant_id = row.get("restaurant_id", "")
            restaurant_features = self.restaurant_features_lookup.get(
                restaurant_id, self.default_restaurant_features.copy()
            )
            
            # Cart dynamic features
            cart_total = float(row.get("cart_total", 0))
            cart_size = len(cart_indices)
            
            # Calculate avg item price in cart
            if cart_item_ids:
                prices = [self.item_prices.get(item_id, 100) for item_id in cart_item_ids]
                avg_cart_price = np.mean(prices)
            else:
                avg_cart_price = 0.0
            
            # Behavioral features computed from cart_categories
            cart_categories_str = str(row.get("cart_categories", ""))
            cart_categories = set(cart_categories_str.split("|")) if cart_categories_str and cart_categories_str != "nan" else set()
            
            missing_beverage = 1.0 if "beverage" not in cart_categories else 0.0
            missing_dessert = 1.0 if "dessert" not in cart_categories else 0.0
            
            # Heavy meal: 2+ mains or main + side
            main_count = cart_categories_str.count("main") if cart_categories_str else 0
            side_count = cart_categories_str.count("side") if cart_categories_str else 0
            heavy_meal = 1.0 if (main_count >= 2 or (main_count >= 1 and side_count >= 1)) else 0.0
            
            cart_dynamic_features = [
                cart_total / 1000.0,       # Normalize cart total
                cart_size / MAX_CART_SIZE,  # Normalize cart size
                avg_cart_price / 500.0,     # Normalize avg price
                missing_beverage,           # Already 0/1
                missing_dessert,            # Already 0/1
                heavy_meal                  # Already 0/1
            ]
            
            # Context features
            hour = int(row.get("hour", 12))
            meal_type = str(row.get("meal_type", "lunch"))
            user_type = str(row.get("user_type", "moderate"))
            
            context_features = [
                hour / 24.0,  # Normalized hour
                float(MEAL_TYPE_MAP.get(meal_type, 1)),
                float(USER_TYPE_MAP.get(user_type, 1))
            ]
            
            # Candidate category one-hot features (main, dessert, beverage, side)
            candidate_category_idx = self.item_categories.get(candidate_id, 7)
            is_main = 1.0 if candidate_category_idx == 0 else 0.0
            is_dessert = 1.0 if candidate_category_idx == 2 else 0.0
            is_beverage = 1.0 if candidate_category_idx == 3 else 0.0
            is_side = 1.0 if candidate_category_idx == 4 else 0.0
            
            context_features.extend([is_main, is_dessert, is_beverage, is_side])
            
            # Timestamp for sorting
            timestamp = str(row.get("timestamp", ""))
            
            # Create sample
            sample = TrainingSample(
                cart_indices=cart_indices,
                candidate_index=candidate_idx,
                label=label,
                user_features=user_features,
                restaurant_features=restaurant_features,
                cart_dynamic_features=cart_dynamic_features,
                context_features=context_features,
                timestamp=timestamp
            )
            
            self.data.append(sample)
    
    def __len__(self) -> int:
        return len(self.data)
    
    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        """
        Get a single training sample.
        
        Returns dict with all required tensors (except batching/padding).
        """
        sample = self.data[idx]
        
        return {
            "cart_indices": sample.cart_indices,  # Variable length list
            "candidate_index": sample.candidate_index,
            "label": sample.label,
            "user_features": torch.tensor(sample.user_features, dtype=torch.float32),
            "restaurant_features": torch.tensor(sample.restaurant_features, dtype=torch.float32),
            "cart_dynamic_features": torch.tensor(sample.cart_dynamic_features, dtype=torch.float32),
            "context_features": torch.tensor(sample.context_features, dtype=torch.float32),
        }


# -----------------------------------------------------------------------------
# Collate Function (Dynamic Padding)
# -----------------------------------------------------------------------------

def collate_fn(batch: List[Dict]) -> Dict[str, torch.Tensor]:
    """
    Custom collate function for variable-length cart sequences.
    
    Pads cart sequences to the maximum length in the batch (not global max).
    This is more memory-efficient than padding to a fixed maximum size.
    
    Args:
        batch: List of samples from CartDataset.__getitem__
    
    Returns:
        Batched tensors with padding applied
    """
    batch_size = len(batch)
    
    # Find max cart length in this batch
    cart_lengths = [len(sample["cart_indices"]) for sample in batch]
    max_cart_len = max(cart_lengths) if cart_lengths else 0
    max_cart_len = max(max_cart_len, 1)  # At least 1 to avoid empty tensors
    
    # Initialize padded cart indices (0 is padding index)
    cart_indices = torch.zeros(batch_size, max_cart_len, dtype=torch.long)
    
    # Fill in actual values
    for i, sample in enumerate(batch):
        indices = sample["cart_indices"]
        if indices:
            cart_indices[i, :len(indices)] = torch.tensor(indices, dtype=torch.long)
    
    # Create padding mask (True = padding position)
    cart_lengths_tensor = torch.tensor(cart_lengths, dtype=torch.long)
    cart_mask = create_cart_mask(cart_lengths_tensor, max_cart_len)
    
    # Stack other tensors
    candidate_indices = torch.tensor(
        [s["candidate_index"] for s in batch], dtype=torch.long
    )
    labels = torch.tensor(
        [s["label"] for s in batch], dtype=torch.float32
    ).unsqueeze(1)  # (batch, 1)
    
    user_features = torch.stack([s["user_features"] for s in batch])
    restaurant_features = torch.stack([s["restaurant_features"] for s in batch])
    cart_dynamic_features = torch.stack([s["cart_dynamic_features"] for s in batch])
    context_features = torch.stack([s["context_features"] for s in batch])
    
    return {
        "cart_indices": cart_indices,
        "candidate_indices": candidate_indices,
        "labels": labels,
        "user_features": user_features,
        "restaurant_features": restaurant_features,
        "cart_dynamic_features": cart_dynamic_features,
        "context_features": context_features,
        "cart_mask": cart_mask,
    }


# -----------------------------------------------------------------------------
# Training Functions
# -----------------------------------------------------------------------------

def compute_class_weights(labels: torch.Tensor) -> torch.Tensor:
    """
    Compute class weights for imbalanced binary classification.
    
    Uses inverse frequency weighting to handle class imbalance.
    
    Args:
        labels: Binary labels tensor
    
    Returns:
        pos_weight for BCEWithLogitsLoss (weight for positive class)
    """
    num_pos = labels.sum().item()
    num_neg = len(labels) - num_pos
    
    if num_pos == 0 or num_neg == 0:
        return torch.tensor(1.0)
    
    # pos_weight = num_neg / num_pos
    pos_weight = num_neg / num_pos
    
    logger.info(f"Class distribution: pos={num_pos:,}, neg={num_neg:,}")
    logger.info(f"Positive class weight: {pos_weight:.3f}")
    logger.info(f"[DEBUG] pos_weight = {pos_weight:.6f}")
    
    return torch.tensor(pos_weight)


def train_epoch(
    model: CartAddToCartModel,
    dataloader: DataLoader,
    optimizer: torch.optim.Optimizer,
    criterion: nn.Module,
    device: str = "cpu"
) -> Tuple[float, List[float], List[int]]:
    """
    Train for one epoch.
    
    Returns:
        avg_loss: Average loss over batches
        all_preds: All prediction probabilities
        all_labels: All true labels
    """
    model.train()
    total_loss = 0.0
    num_batches = 0
    first_batch_logged = False
    
    all_preds = []
    all_labels = []
    
    for batch in dataloader:
        # Move to device
        cart_indices = batch["cart_indices"].to(device)
        candidate_indices = batch["candidate_indices"].to(device)
        labels = batch["labels"].to(device)
        user_features = batch["user_features"].to(device)
        restaurant_features = batch["restaurant_features"].to(device)
        cart_dynamic_features = batch["cart_dynamic_features"].to(device)
        context_features = batch["context_features"].to(device)
        cart_mask = batch["cart_mask"].to(device)
        
        # Forward pass
        optimizer.zero_grad()
        logits = model(
            cart_indices, candidate_indices,
            user_features, restaurant_features,
            cart_dynamic_features, context_features,
            cart_mask
        )
        
        # Compute loss
        loss = criterion(logits, labels)
        
        # Backward pass
        loss.backward()
        
        # Gradient clipping
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        
        optimizer.step()
        
        # Track metrics
        total_loss += loss.item()
        num_batches += 1
        
        # Store predictions for metrics
        with torch.no_grad():
            preds = torch.sigmoid(logits).squeeze().cpu().numpy()
            labs = labels.squeeze().cpu().numpy()
            
            # DEBUG: Log first batch prediction stats
            if not first_batch_logged:
                pred_mean = preds.mean() if preds.ndim > 0 else preds.item()
                pred_std = preds.std() if preds.ndim > 0 else 0.0
                label_mean = labs.mean() if labs.ndim > 0 else labs.item()
                logger.info(f"[DEBUG] First batch prediction mean: {pred_mean:.4f}, std: {pred_std:.4f}")
                logger.info(f"[DEBUG] First batch label mean: {label_mean:.4f}")
                first_batch_logged = True
            
            if preds.ndim == 0:
                preds = np.array([preds.item()])
                labs = np.array([labs.item()])
            
            all_preds.extend(preds.tolist())
            all_labels.extend(labs.astype(int).tolist())
    
    avg_loss = total_loss / max(num_batches, 1)
    return avg_loss, all_preds, all_labels


@torch.no_grad()
def evaluate(
    model: CartAddToCartModel,
    dataloader: DataLoader,
    criterion: nn.Module,
    device: str = "cpu"
) -> Tuple[float, float, float, List[float], List[int]]:
    """
    Evaluate model on validation set.
    
    Returns:
        avg_loss: Average loss
        auc: ROC-AUC score
        pr_auc: PR-AUC score
        all_preds: Prediction probabilities
        all_labels: True labels
    """
    model.eval()
    total_loss = 0.0
    num_batches = 0
    
    all_preds = []
    all_labels = []
    
    for batch in dataloader:
        cart_indices = batch["cart_indices"].to(device)
        candidate_indices = batch["candidate_indices"].to(device)
        labels = batch["labels"].to(device)
        user_features = batch["user_features"].to(device)
        restaurant_features = batch["restaurant_features"].to(device)
        cart_dynamic_features = batch["cart_dynamic_features"].to(device)
        context_features = batch["context_features"].to(device)
        cart_mask = batch["cart_mask"].to(device)
        
        logits = model(
            cart_indices, candidate_indices,
            user_features, restaurant_features,
            cart_dynamic_features, context_features,
            cart_mask
        )
        
        loss = criterion(logits, labels)
        total_loss += loss.item()
        num_batches += 1
        
        preds = torch.sigmoid(logits).squeeze().cpu().numpy()
        labs = labels.squeeze().cpu().numpy()
        
        if preds.ndim == 0:
            preds = np.array([preds.item()])
            labs = np.array([labs.item()])
        
        all_preds.extend(preds.tolist())
        all_labels.extend(labs.astype(int).tolist())
    
    avg_loss = total_loss / max(num_batches, 1)
    
    # Compute metrics
    try:
        auc = roc_auc_score(all_labels, all_preds)
    except ValueError:
        auc = 0.5  # Only one class present
    
    try:
        pr_auc = average_precision_score(all_labels, all_preds)
    except ValueError:
        pr_auc = 0.0
    
    return avg_loss, auc, pr_auc, all_preds, all_labels


def save_checkpoint(
    model: CartAddToCartModel,
    optimizer: torch.optim.Optimizer,
    epoch: int,
    metrics: Dict,
    config: Dict,
    checkpoint_path: Path
):
    """Save training checkpoint."""
    checkpoint = {
        "epoch": epoch,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "metrics": metrics,
        "config": config,
        "timestamp": datetime.now().isoformat()
    }
    torch.save(checkpoint, checkpoint_path)
    logger.info(f"Checkpoint saved: {checkpoint_path}")


# -----------------------------------------------------------------------------
# Data Loading
# -----------------------------------------------------------------------------

def load_item_mapping(mapping_path: Path) -> Dict[str, int]:
    """
    Load item ID to embedding index mapping.
    
    The mapping file contains {'item_to_idx': {...}, 'idx_to_item': {...}, 'metadata': {...}}.
    """
    with open(mapping_path, "rb") as f:
        data = pickle.load(f)
    
    # Handle different formats
    if isinstance(data, dict) and "item_to_idx" in data:
        # New format with explicit item_to_idx mapping
        item_to_idx = data["item_to_idx"]
    elif isinstance(data, list):
        # Old format: [idx_to_item_dict, metadata]
        idx_to_item = data[0]
        item_to_idx = {item_id: idx for idx, item_id in idx_to_item.items()}
    else:
        # Assume it's a direct idx_to_item dict
        idx_to_item = data
        item_to_idx = {item_id: idx for idx, item_id in idx_to_item.items()}
    
    logger.info(f"Loaded item mapping: {len(item_to_idx):,} items")
    return item_to_idx


def load_data(
    sample_size: int = DEFAULT_SAMPLE_SIZE,
    val_ratio: float = DEFAULT_VAL_RATIO
) -> Tuple[CartDataset, CartDataset, Dict[str, int]]:
    """
    Load and preprocess training data.
    
    Args:
        sample_size: Number of rows to load (for memory efficiency)
        val_ratio: Fraction of data for validation (time-based split)
    
    Returns:
        train_dataset, val_dataset, item_to_idx mapping
    """
    logger.info("=" * 60)
    logger.info("Loading Training Data")
    logger.info("=" * 60)
    
    # Load item mapping
    item_to_idx = load_item_mapping(ITEM_MAPPING_PATH)
    
    # Load cart events (sample for memory efficiency)
    logger.info(f"Loading cart events (sample_size={sample_size:,})...")
    
    # Read in chunks to get timestamps for time-based split
    chunks = []
    rows_read = 0
    
    for chunk in pd.read_csv(CART_EVENTS_PATH, chunksize=500_000):
        chunks.append(chunk)
        rows_read += len(chunk)
        if rows_read >= sample_size:
            break
        if rows_read % 1_000_000 == 0:
            logger.info(f"  Read {rows_read:,} rows...")
    
    df = pd.concat(chunks, ignore_index=True)
    df = df.head(sample_size)  # Ensure exact size
    
    logger.info(f"Loaded {len(df):,} cart events")
    
    # Compute label distribution
    label_counts = df["label"].value_counts()
    logger.info(f"Label distribution: {label_counts.to_dict()}")
    
    # Sort by timestamp for time-based split
    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
    df = df.sort_values("timestamp").reset_index(drop=True)
    
    # Time-based split
    split_idx = int(len(df) * (1 - val_ratio))
    train_df = df.iloc[:split_idx].copy()
    val_df = df.iloc[split_idx:].copy()
    
    # DEBUG: Print label means
    train_label_mean = train_df["label"].mean()
    val_label_mean = val_df["label"].mean()
    logger.info(f"[DEBUG] Train label mean: {train_label_mean:.4f}")
    logger.info(f"[DEBUG] Val label mean: {val_label_mean:.4f}")
    
    logger.info(f"Train/Val split: {len(train_df):,} / {len(val_df):,}")
    
    # Load auxiliary data - require normalized parquet files (no fallback)
    logger.info("Loading auxiliary data...")
    
    users_df = None
    if USER_FEATURES_PATH.exists():
        users_df = pd.read_parquet(USER_FEATURES_PATH)
        logger.info(f"  Users (normalized parquet): {len(users_df):,}")
        norm_cols = [c for c in users_df.columns if c.endswith("_norm")]
        logger.info(f"    Normalized columns: {norm_cols}")
        if not norm_cols:
            raise ValueError(f"User parquet must have _norm columns. Regenerate with feature_builder.py")
    else:
        raise FileNotFoundError(f"User features parquet not found: {USER_FEATURES_PATH}")
    
    restaurants_df = None
    if RESTAURANT_FEATURES_PATH.exists():
        restaurants_df = pd.read_parquet(RESTAURANT_FEATURES_PATH)
        logger.info(f"  Restaurants (normalized parquet): {len(restaurants_df):,}")
        norm_cols = [c for c in restaurants_df.columns if c.endswith("_norm")]
        logger.info(f"    Normalized columns: {norm_cols}")
        if not norm_cols:
            raise ValueError(f"Restaurant parquet must have _norm columns. Regenerate with feature_builder.py")
    else:
        raise FileNotFoundError(f"Restaurant features parquet not found: {RESTAURANT_FEATURES_PATH}")
    
    menu_items_df = None
    if MENU_ITEMS_PATH.exists():
        menu_items_df = pd.read_csv(MENU_ITEMS_PATH)
        logger.info(f"  Menu items: {len(menu_items_df):,}")
    
    # Build datasets
    logger.info("Building datasets...")
    
    train_dataset = CartDataset(
        train_df, item_to_idx,
        user_features_df=users_df,
        restaurant_features_df=restaurants_df,
        menu_items_df=menu_items_df
    )
    
    val_dataset = CartDataset(
        val_df, item_to_idx,
        user_features_df=users_df,
        restaurant_features_df=restaurants_df,
        menu_items_df=menu_items_df
    )
    
    # Cleanup
    del df, train_df, val_df, chunks
    gc.collect()
    
    return train_dataset, val_dataset, item_to_idx


# -----------------------------------------------------------------------------
# Main Training Loop
# -----------------------------------------------------------------------------

def train(
    batch_size: int = DEFAULT_BATCH_SIZE,
    epochs: int = DEFAULT_EPOCHS,
    lr: float = DEFAULT_LR,
    sample_size: int = DEFAULT_SAMPLE_SIZE,
    val_ratio: float = DEFAULT_VAL_RATIO,
    checkpoint_freq: int = 2,
    device: str = "cpu",
    disable_transformer: bool = False
):
    """
    Main training function.
    
    Args:
        batch_size: Training batch size
        epochs: Number of training epochs
        lr: Learning rate
        sample_size: Number of training samples to use
        val_ratio: Validation set ratio (time-based split)
        checkpoint_freq: Save checkpoint every N epochs
        device: Training device ('cpu' or 'cuda')
        disable_transformer: If True, use mean pooling instead of transformer
    """
    logger.info("=" * 60)
    logger.info("Cart Add-to-Cart Model Training")
    logger.info("=" * 60)
    logger.info(f"Device: {device}")
    logger.info(f"Batch size: {batch_size:,}")
    logger.info(f"Epochs: {epochs}")
    logger.info(f"Learning rate: {lr}")
    logger.info(f"Sample size: {sample_size:,}")
    logger.info(f"Transformer: {'DISABLED' if disable_transformer else 'enabled'}")
    
    # Create directories
    CHECKPOINTS_DIR.mkdir(parents=True, exist_ok=True)
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    
    # Load data
    train_dataset, val_dataset, item_to_idx = load_data(sample_size, val_ratio)
    
    # Create data loaders
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        collate_fn=collate_fn,
        num_workers=0,  # CPU training
        pin_memory=False
    )
    
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size * 2,  # Larger batch for eval
        shuffle=False,
        collate_fn=collate_fn,
        num_workers=0
    )
    
    logger.info(f"Train batches: {len(train_loader):,}")
    logger.info(f"Val batches: {len(val_loader):,}")
    
    # Compute class weights for imbalanced data
    all_labels = torch.tensor([s.label for s in train_dataset.data])
    pos_weight = compute_class_weights(all_labels)
    
    # Compute prior probability for bias initialization
    prior_prob = all_labels.float().mean().item()
    logger.info(f"[DEBUG] Prior probability (for bias init): {prior_prob:.4f}")
    
    # Initialize model
    logger.info("Initializing model...")
    model = CartAddToCartModel(
        item_embeddings_path=EMBEDDINGS_PATH,
        user_feature_dim=7,
        restaurant_feature_dim=5,
        cart_dynamic_feature_dim=6,  # Now includes missing_beverage, missing_dessert, heavy_meal
        context_feature_dim=7,  # hour, meal_type, user_type + 4 candidate category one-hot features
        freeze_embeddings=True,
        disable_transformer=disable_transformer,
        prior_prob=prior_prob
    )
    model.to(device)
    
    # Loss function with class weighting
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight.to(device))
    
    # Optimizer
    optimizer = AdamW(
        model.parameters(),
        lr=lr,
        weight_decay=0.01,
        betas=(0.9, 0.999)
    )
    
    # Learning rate scheduler
    scheduler = ReduceLROnPlateau(
        optimizer,
        mode="max",  # Maximize AUC
        factor=0.5,
        patience=2
    )
    
    # Training config for checkpointing
    config = {
        "batch_size": batch_size,
        "epochs": epochs,
        "lr": lr,
        "sample_size": sample_size,
        "val_ratio": val_ratio,
        "embeddings_path": str(EMBEDDINGS_PATH),
        "user_feature_dim": 7,
        "restaurant_feature_dim": 5,
        "cart_dynamic_feature_dim": 6,
        "context_feature_dim": 7,  # hour, meal_type, user_type + 4 candidate category features
        "embedding_dim": 64,
    }
    
    # Training history
    history = {
        "train_loss": [],
        "val_loss": [],
        "val_auc": [],
        "val_pr_auc": [],
        "lr": []
    }
    
    best_auc = 0.0
    best_epoch = 0
    best_pr_auc = 0.0
    patience_counter = 0
    early_stop_patience = 2  # Stop if no improvement for 2 epochs
    
    logger.info("\nStarting training...")
    logger.info("-" * 60)
    logger.info(f"Early stopping: patience={early_stop_patience} epochs on val AUC")
    
    training_start = time.time()
    
    for epoch in range(1, epochs + 1):
        epoch_start = time.time()
        
        # Train
        train_loss, train_preds, train_labels = train_epoch(
            model, train_loader, optimizer, criterion, device
        )
        
        # Evaluate
        val_loss, val_auc, val_pr_auc, val_preds, val_labels = evaluate(
            model, val_loader, criterion, device
        )
        
        # Update scheduler
        scheduler.step(val_auc)
        
        # Track history
        current_lr = optimizer.param_groups[0]["lr"]
        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["val_auc"].append(val_auc)
        history["val_pr_auc"].append(val_pr_auc)
        history["lr"].append(current_lr)
        
        epoch_time = time.time() - epoch_start
        
        # Logging
        logger.info(
            f"Epoch {epoch:2d}/{epochs} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"AUC: {val_auc:.4f} | "
            f"PR-AUC: {val_pr_auc:.4f} | "
            f"LR: {current_lr:.2e} | "
            f"Time: {epoch_time:.1f}s"
        )
        
        # Best model checkpoint
        if val_auc > best_auc:
            best_auc = val_auc
            best_pr_auc = val_pr_auc
            best_epoch = epoch
            patience_counter = 0  # Reset patience counter
            best_checkpoint_path = CHECKPOINTS_DIR / "best_model_final.pt"
            save_checkpoint(
                model, optimizer, epoch,
                {"val_auc": val_auc, "val_pr_auc": val_pr_auc, "val_loss": val_loss},
                config, best_checkpoint_path
            )
            logger.info(f"  ★ New best model (AUC: {val_auc:.4f}, PR-AUC: {val_pr_auc:.4f})")
        else:
            patience_counter += 1
            logger.info(f"  No improvement ({patience_counter}/{early_stop_patience})")
        
        # Regular checkpoint
        if epoch % checkpoint_freq == 0:
            checkpoint_path = CHECKPOINTS_DIR / f"checkpoint_epoch_{epoch}.pt"
            save_checkpoint(
                model, optimizer, epoch,
                {"val_auc": val_auc, "val_pr_auc": val_pr_auc, "val_loss": val_loss},
                config, checkpoint_path
            )
        
        # Early stopping check
        if patience_counter >= early_stop_patience:
            logger.info(f"\n⚠️  Early stopping triggered at epoch {epoch}")
            logger.info(f"   No improvement in val AUC for {early_stop_patience} epochs")
            break
    
    total_time = time.time() - training_start
    
    # Training summary
    logger.info("\n" + "=" * 60)
    logger.info("TRAINING COMPLETE - FINAL METRICS SUMMARY")
    logger.info("=" * 60)
    logger.info(f"Total training time: {total_time/60:.1f} minutes ({total_time:.1f}s)")
    logger.info(f"Epochs completed: {len(history['train_loss'])}")
    logger.info(f"Best epoch: {best_epoch}")
    logger.info("-" * 60)
    logger.info("BEST MODEL METRICS:")
    logger.info(f"  ★ Best Val AUC:    {best_auc:.6f}")
    logger.info(f"  ★ Best Val PR-AUC: {best_pr_auc:.6f}")
    logger.info("-" * 60)
    logger.info("FINAL EPOCH METRICS:")
    logger.info(f"  Val Loss:   {history['val_loss'][-1]:.6f}")
    logger.info(f"  Val AUC:    {history['val_auc'][-1]:.6f}")
    logger.info(f"  Val PR-AUC: {history['val_pr_auc'][-1]:.6f}")
    logger.info("-" * 60)
    logger.info("TRAINING LOSS PER EPOCH:")
    for i, loss in enumerate(history['train_loss'], 1):
        logger.info(f"  Epoch {i}: {loss:.6f}")
    logger.info("=" * 60)
    
    # Save final checkpoint
    final_checkpoint_path = CHECKPOINTS_DIR / "final_model.pt"
    save_checkpoint(
        model, optimizer, epochs,
        history, config, final_checkpoint_path
    )
    
    # Save training history
    history_path = LOGS_DIR / "training_history.pkl"
    with open(history_path, "wb") as f:
        pickle.dump(history, f)
    logger.info(f"Training history saved: {history_path}")
    
    return model, history


# -----------------------------------------------------------------------------
# CLI Entry Point
# -----------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Train Cart Add-to-Cart Prediction Model"
    )
    
    parser.add_argument(
        "--batch-size", type=int, default=DEFAULT_BATCH_SIZE,
        help=f"Training batch size (default: {DEFAULT_BATCH_SIZE})"
    )
    parser.add_argument(
        "--epochs", type=int, default=DEFAULT_EPOCHS,
        help=f"Number of training epochs (default: {DEFAULT_EPOCHS})"
    )
    parser.add_argument(
        "--lr", type=float, default=DEFAULT_LR,
        help=f"Learning rate (default: {DEFAULT_LR})"
    )
    parser.add_argument(
        "--sample-size", type=int, default=DEFAULT_SAMPLE_SIZE,
        help=f"Number of training samples (default: {DEFAULT_SAMPLE_SIZE:,})"
    )
    parser.add_argument(
        "--val-ratio", type=float, default=DEFAULT_VAL_RATIO,
        help=f"Validation ratio (default: {DEFAULT_VAL_RATIO})"
    )
    parser.add_argument(
        "--checkpoint-freq", type=int, default=2,
        help="Checkpoint every N epochs (default: 2)"
    )
    parser.add_argument(
        "--device", type=str, default="cpu",
        choices=["cpu", "cuda", "mps"],
        help="Training device (default: cpu)"
    )
    parser.add_argument(
        "--disable-transformer", action="store_true",
        help="Disable transformer, use mean pooling instead (for debugging)"
    )
    
    args = parser.parse_args()
    
    # Validate device
    device = args.device
    if device == "cuda" and not torch.cuda.is_available():
        logger.warning("CUDA not available, falling back to CPU")
        device = "cpu"
    if device == "mps" and not torch.backends.mps.is_available():
        logger.warning("MPS not available, falling back to CPU")
        device = "cpu"
    
    # Run training
    train(
        batch_size=args.batch_size,
        epochs=args.epochs,
        lr=args.lr,
        sample_size=args.sample_size,
        val_ratio=args.val_ratio,
        checkpoint_freq=args.checkpoint_freq,
        device=device,
        disable_transformer=args.disable_transformer
    )


if __name__ == "__main__":
    main()
